definitions:
  request.ReqCreate:
    properties:
      max_count:
        type: integer
      min_count:
        type: integer
      name:
        type: string
      password:
        type: string
    required:
    - max_count
    - min_count
    - name
    type: object
  request.ReqDora:
    properties:
      cardColor:
        type: string
      cardID:
        type: integer
      cardName:
        type: string
      cardState:
        type: string
      roomID:
        type: integer
    type: object
  request.ReqJoin:
    properties:
      password:
        type: string
      roomID:
        type: integer
    required:
    - roomID
    type: object
  request.ReqOut:
    properties:
      roomID:
        type: integer
    type: object
  request.ReqReady:
    properties:
      playerState:
        type: string
      roomID:
        type: integer
    type: object
  request.ReqSignin:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  request.ReqSignup:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  request.ReqStart:
    properties:
      roomID:
        type: integer
      state:
        type: string
    type: object
  response.ResSignin:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
info:
  contact: {}
paths:
  /v0.1/auth/signin:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_EXIST : 유저가 존재하지 않음
        USER_ALREADY_EXISTED : 유저가 이미 존재

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: 이메일, 비밀번호
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqSignin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResSignin'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 로그인
      tags:
      - auth
  /v0.1/auth/signup:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_EXIST : 유저가 존재하지 않음
        USER_ALREADY_EXISTED : 유저가 이미 존재

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: 이름, 이메일, 비밀번호
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqSignup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 회원 가입
      tags:
      - auth
  /v0.1/game/dora:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        NOT_OWNER : 방장이 시작 요청을 하지 않음
        NOT_FIRST_PLAYER : 첫 플레이어가 아님

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqDora'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 도라 선택하기
      tags:
      - game
  /v0.1/game/start:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        NOT_ALL_USERS_READY : 모든 유저가 준비되지 않음

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqStart'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 게임 시작
      tags:
      - game
  /v0.1/room/create:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_FOUND : 유저를 찾을 수 없음
        USER_ALREADY_EXISTED : 이미 존재하는 유저
        ROOM_NOT_FOUND : 방을 찾을 수 없음
        ROOM_FULL : 방이 꽉 참
        ROOM_USER_NOT_FOUND : 방 유저를 찾을 수 없음

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
        PLAYER_STATE_CHANGE_FAILED : 플레이어 상태 변경 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 방 생성
      tags:
      - room
  /v0.1/room/join:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_FOUND : 유저를 찾을 수 없음
        USER_ALREADY_EXISTED : 이미 존재하는 유저
        ROOM_NOT_FOUND : 방을 찾을 수 없음
        ROOM_FULL : 방이 꽉 참
        ROOM_USER_NOT_FOUND : 방 유저를 찾을 수 없음

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
        PLAYER_STATE_CHANGE_FAILED : 플레이어 상태 변경 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqJoin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 방 참여
      tags:
      - room
  /v0.1/room/out:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_FOUND : 유저를 찾을 수 없음
        USER_ALREADY_EXISTED : 이미 존재하는 유저
        ROOM_NOT_FOUND : 방을 찾을 수 없음
        ROOM_FULL : 방이 꽉 참
        ROOM_USER_NOT_FOUND : 방 유저를 찾을 수 없음

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
        PLAYER_STATE_CHANGE_FAILED : 플레이어 상태 변경 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqOut'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 방 나가기
      tags:
      - room
  /v0.1/room/ready:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_FOUND : 유저를 찾을 수 없음
        USER_ALREADY_EXISTED : 이미 존재하는 유저
        ROOM_NOT_FOUND : 방을 찾을 수 없음
        ROOM_FULL : 방이 꽉 참
        ROOM_USER_NOT_FOUND : 방 유저를 찾을 수 없음

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
        PLAYER_STATE_CHANGE_FAILED : 플레이어 상태 변경 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqReady'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 게임 준비 상태 변경
      tags:
      - room
swagger: "2.0"
