definitions:
  request.Card:
    properties:
      cardID:
        type: integer
      roomID:
        type: integer
      state:
        type: string
      userID:
        type: integer
    type: object
  request.ReqCreate:
    properties:
      maxCount:
        type: integer
      minCount:
        type: integer
      name:
        type: string
      password:
        type: string
    required:
    - maxCount
    - minCount
    - name
    type: object
  request.ReqDiscard:
    properties:
      cardID:
        type: integer
      cardState:
        type: string
      roomID:
        type: integer
      userID:
        type: integer
    type: object
  request.ReqDora:
    properties:
      cardColor:
        type: string
      cardID:
        type: integer
      cardName:
        type: string
      cardState:
        type: string
      roomID:
        type: integer
    type: object
  request.ReqJoin:
    properties:
      password:
        type: string
      roomID:
        type: integer
    required:
    - roomID
    type: object
  request.ReqLoan:
    properties:
      loanCardID:
        type: integer
      loanUserID:
        type: integer
      roomID:
        type: integer
    type: object
  request.ReqNextTurn:
    properties:
      playerState:
        type: string
      roomID:
        type: integer
      turnNumber:
        type: integer
      userID:
        type: integer
    type: object
  request.ReqOut:
    properties:
      roomID:
        type: integer
    type: object
  request.ReqOwnership:
    properties:
      cards:
        items:
          $ref: '#/definitions/request.Card'
        type: array
    type: object
  request.ReqReady:
    properties:
      playerState:
        type: string
      roomID:
        type: integer
    type: object
  request.ReqScoreCalculate:
    properties:
      cards:
        items:
          $ref: '#/definitions/request.ScoreCard'
        type: array
      roomID:
        type: integer
    type: object
  request.ReqSignin:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  request.ReqSignup:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  request.ReqStart:
    properties:
      roomID:
        type: integer
      state:
        type: string
    type: object
  request.ReqWinRequest:
    properties:
      roomID:
        type: integer
      score:
        type: integer
      userID:
        type: integer
    type: object
  request.ScoreCard:
    properties:
      cardID:
        type: integer
      color:
        type: string
      name:
        type: string
      state:
        type: string
    type: object
  response.ListRoom:
    properties:
      created:
        type: integer
      currentCount:
        type: integer
      id:
        type: integer
      maxCount:
        type: integer
      minCount:
        type: integer
      name:
        type: string
      owner:
        type: string
      password:
        type: string
      state:
        type: string
    type: object
  response.ResListRoom:
    properties:
      rooms:
        items:
          $ref: '#/definitions/response.ListRoom'
        type: array
      total:
        type: integer
    type: object
  response.ResScoreCalculate:
    properties:
      bonuses:
        items:
          type: string
        type: array
      score:
        type: integer
    type: object
  response.ResSignin:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
info:
  contact: {}
paths:
  /v0.1/auth/signin:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_EXIST : 유저가 존재하지 않음
        USER_ALREADY_EXISTED : 유저가 이미 존재

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: 이메일, 비밀번호
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqSignin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResSignin'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 로그인
      tags:
      - auth
  /v0.1/auth/signup:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_EXIST : 유저가 존재하지 않음
        USER_ALREADY_EXISTED : 유저가 이미 존재

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: 이름, 이메일, 비밀번호
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqSignup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 회원 가입
      tags:
      - auth
  /v0.1/game/card/discard:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        NOT_OWNER : 방장이 시작 요청을 하지 않음
        NOT_FIRST_PLAYER : 첫 플레이어가 아님

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqDiscard'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 카드 버리기
      tags:
      - game
  /v0.1/game/card/ownership:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        NOT_OWNER : 방장이 시작 요청을 하지 않음
        NOT_FIRST_PLAYER : 첫 플레이어가 아님

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqOwnership'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 카드 소유하기
      tags:
      - game
  /v0.1/game/dora:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        NOT_OWNER : 방장이 시작 요청을 하지 않음
        NOT_FIRST_PLAYER : 첫 플레이어가 아님

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqDora'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 도라 선택하기
      tags:
      - game
  /v0.1/game/loan:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        NOT_OWNER : 방장이 시작 요청을 하지 않음
        NOT_FIRST_PLAYER : 첫 플레이어가 아님
        NOT_LOAN_CARD : 론할 수 없는 카드

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqLoan'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 론 하기
      tags:
      - game
  /v0.1/game/next-turn:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        NOT_OWNER : 방장이 시작 요청을 하지 않음
        NOT_FIRST_PLAYER : 첫 플레이어가 아님

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqNextTurn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 다음 턴 넘기기
      tags:
      - game
  /v0.1/game/score/calculate:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        NOT_ALL_USERS_READY : 모든 유저가 준비되지 않음

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqScoreCalculate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResScoreCalculate'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 점수 계산하기
      tags:
      - game
  /v0.1/game/start:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        NOT_ALL_USERS_READY : 모든 유저가 준비되지 않음

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqStart'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 게임 시작
      tags:
      - game
  /v0.1/game/win-request:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        NOT_ALL_USERS_READY : 모든 유저가 준비되지 않음

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqWinRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 게임 승리 요청
      tags:
      - game
  /v0.1/room:
    get:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_FOUND : 유저를 찾을 수 없음
        USER_ALREADY_EXISTED : 이미 존재하는 유저
        ROOM_NOT_FOUND : 방을 찾을 수 없음
        ROOM_FULL : 방이 꽉 참
        ROOM_USER_NOT_FOUND : 방 유저를 찾을 수 없음

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
        PLAYER_STATE_CHANGE_FAILED : 플레이어 상태 변경 실패
      parameters:
      - description: 조회할 페이지. 0부터 시작, 누락시 0으로 처리
        in: query
        name: page
        type: integer
      - description: '페이지당 알림 개수. 누락시 10으로 처리 '
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResListRoom'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 방 목록 가져오기
      tags:
      - room
  /v0.1/room/create:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_FOUND : 유저를 찾을 수 없음
        USER_ALREADY_EXISTED : 이미 존재하는 유저
        ROOM_NOT_FOUND : 방을 찾을 수 없음
        ROOM_FULL : 방이 꽉 참
        ROOM_USER_NOT_FOUND : 방 유저를 찾을 수 없음

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
        PLAYER_STATE_CHANGE_FAILED : 플레이어 상태 변경 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 방 생성
      tags:
      - room
  /v0.1/room/join:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_FOUND : 유저를 찾을 수 없음
        USER_ALREADY_EXISTED : 이미 존재하는 유저
        ROOM_NOT_FOUND : 방을 찾을 수 없음
        ROOM_FULL : 방이 꽉 참
        ROOM_USER_NOT_FOUND : 방 유저를 찾을 수 없음

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
        PLAYER_STATE_CHANGE_FAILED : 플레이어 상태 변경 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqJoin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 방 참여
      tags:
      - room
  /v0.1/room/out:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_FOUND : 유저를 찾을 수 없음
        USER_ALREADY_EXISTED : 이미 존재하는 유저
        ROOM_NOT_FOUND : 방을 찾을 수 없음
        ROOM_FULL : 방이 꽉 참
        ROOM_USER_NOT_FOUND : 방 유저를 찾을 수 없음

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
        PLAYER_STATE_CHANGE_FAILED : 플레이어 상태 변경 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqOut'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 방 나가기
      tags:
      - room
  /v0.1/room/ready:
    post:
      description: |-
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류
        USER_NOT_FOUND : 유저를 찾을 수 없음
        USER_ALREADY_EXISTED : 이미 존재하는 유저
        ROOM_NOT_FOUND : 방을 찾을 수 없음
        ROOM_FULL : 방이 꽉 참
        ROOM_USER_NOT_FOUND : 방 유저를 찾을 수 없음

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
        PLAYER_STATE_CHANGE_FAILED : 플레이어 상태 변경 실패
      parameters:
      - description: accessToken
        in: header
        name: tkn
        required: true
        type: string
      - description: json body
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.ReqReady'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 게임 준비 상태 변경
      tags:
      - room
swagger: "2.0"
