root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "cd ./src && swag init && go build -o ../tmp/main ."
  delay = 1000
  exclude_dir = ["tmp", "src/docs"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin =  "PROJECT=frog PORT=8080 ENV=dev IS_LOCAL=true MYSQL_USER=root MYSQL_PASSWORD=examplepassword MYSQL_HOST=0.0.0.0 MYSQL_PORT=3306 MYSQL_DATABASE=frog_dev PG_USER=dev PG_PASSWORD=asdASD123 PG_DB_NAME=frog_dev  ./tmp/main"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
