version: '3.8'

services:
  mysql:
    image: mysql:latest
    hostname: hostname-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: frog_dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: asdASD123
    volumes:
      - mysql_data:/var/lib/mysql
# postresql service here
  postgres:
    image: postgres:latest
    hostname: hostname-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: asdASD123
      POSTGRES_DB: frog_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  mysql_data:
  postgres_data:


