version: '3.8'

services:
  mysql:
    image: mysql:latest
    hostname: hostname-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: frog_dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: asdASD123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: