// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IGoogleOauthAuthUseCase is an autogenerated mock type for the IGoogleOauthAuthUseCase type
type IGoogleOauthAuthUseCase struct {
	mock.Mock
}

// GoogleOauth provides a mock function with given fields: c
func (_m *IGoogleOauthAuthUseCase) GoogleOauth(c context.Context) (string, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GoogleOauth")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIGoogleOauthAuthUseCase creates a new instance of IGoogleOauthAuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGoogleOauthAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGoogleOauthAuthUseCase {
	mock := &IGoogleOauthAuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
