// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// IGoogleOauthCallbackAuthHandler is an autogenerated mock type for the IGoogleOauthCallbackAuthHandler type
type IGoogleOauthCallbackAuthHandler struct {
	mock.Mock
}

// GoogleOauthCallback provides a mock function with given fields: c
func (_m *IGoogleOauthCallbackAuthHandler) GoogleOauthCallback(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GoogleOauthCallback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIGoogleOauthCallbackAuthHandler creates a new instance of IGoogleOauthCallbackAuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGoogleOauthCallbackAuthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGoogleOauthCallbackAuthHandler {
	mock := &IGoogleOauthCallbackAuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
