// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IGoogleOauthAuthRepository is an autogenerated mock type for the IGoogleOauthAuthRepository type
type IGoogleOauthAuthRepository struct {
	mock.Mock
}

// NewIGoogleOauthAuthRepository creates a new instance of IGoogleOauthAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGoogleOauthAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGoogleOauthAuthRepository {
	mock := &IGoogleOauthAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
