// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ILogoutAuthRepository is an autogenerated mock type for the ILogoutAuthRepository type
type ILogoutAuthRepository struct {
	mock.Mock
}

// FindOneAndUpdateUser provides a mock function with given fields: ctx, uID
func (_m *ILogoutAuthRepository) FindOneAndUpdateUser(ctx context.Context, uID uint) error {
	ret := _m.Called(ctx, uID)

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndUpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, uID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewILogoutAuthRepository creates a new instance of ILogoutAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewILogoutAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ILogoutAuthRepository {
	mock := &ILogoutAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
