// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ILogoutAuthHandler is an autogenerated mock type for the ILogoutAuthHandler type
type ILogoutAuthHandler struct {
	mock.Mock
}

// Logout provides a mock function with given fields: c
func (_m *ILogoutAuthHandler) Logout(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewILogoutAuthHandler creates a new instance of ILogoutAuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewILogoutAuthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ILogoutAuthHandler {
	mock := &ILogoutAuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
