// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	request "main/features/auth/model/request"

	mock "github.com/stretchr/testify/mock"

	response "main/features/auth/model/response"
)

// IReissueAuthUseCase is an autogenerated mock type for the IReissueAuthUseCase type
type IReissueAuthUseCase struct {
	mock.Mock
}

// Reissue provides a mock function with given fields: c, req
func (_m *IReissueAuthUseCase) Reissue(c context.Context, req *request.ReqReissue) (response.ResReissue, error) {
	ret := _m.Called(c, req)

	if len(ret) == 0 {
		panic("no return value specified for Reissue")
	}

	var r0 response.ResReissue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ReqReissue) (response.ResReissue, error)); ok {
		return rf(c, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.ReqReissue) response.ResReissue); ok {
		r0 = rf(c, req)
	} else {
		r0 = ret.Get(0).(response.ResReissue)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.ReqReissue) error); ok {
		r1 = rf(c, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIReissueAuthUseCase creates a new instance of IReissueAuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIReissueAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IReissueAuthUseCase {
	mock := &IReissueAuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
