// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ISigninAuthRepository is an autogenerated mock type for the ISigninAuthRepository type
type ISigninAuthRepository struct {
	mock.Mock
}

// FindOneUserAuth provides a mock function with given fields: ctx, name
func (_m *ISigninAuthRepository) FindOneUserAuth(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindOneUserAuth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewISigninAuthRepository creates a new instance of ISigninAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISigninAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISigninAuthRepository {
	mock := &ISigninAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
