// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	mysql "main/utils/db/mysql"

	mock "github.com/stretchr/testify/mock"
)

// ISigninAuthRepository is an autogenerated mock type for the ISigninAuthRepository type
type ISigninAuthRepository struct {
	mock.Mock
}

// FindOneAndUpdateUser provides a mock function with given fields: ctx, email, password
func (_m *ISigninAuthRepository) FindOneAndUpdateUser(ctx context.Context, email string, password string) (mysql.Users, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndUpdateUser")
	}

	var r0 mysql.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (mysql.Users, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) mysql.Users); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(mysql.Users)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewISigninAuthRepository creates a new instance of ISigninAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISigninAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISigninAuthRepository {
	mock := &ISigninAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
