// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"
	mysql "main/utils/db/mysql"

	mock "github.com/stretchr/testify/mock"
)

// ISignupAuthRepository is an autogenerated mock type for the ISignupAuthRepository type
type ISignupAuthRepository struct {
	mock.Mock
}

// InsertOneUser provides a mock function with given fields: ctx, user
func (_m *ISignupAuthRepository) InsertOneUser(ctx context.Context, user mysql.Users) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for InsertOneUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, mysql.Users) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserCheckByEmail provides a mock function with given fields: ctx, email
func (_m *ISignupAuthRepository) UserCheckByEmail(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for UserCheckByEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewISignupAuthRepository creates a new instance of ISignupAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISignupAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISignupAuthRepository {
	mock := &ISignupAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
