// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ISignupAuthHandler is an autogenerated mock type for the ISignupAuthHandler type
type ISignupAuthHandler struct {
	mock.Mock
}

// Signup provides a mock function with given fields: c
func (_m *ISignupAuthHandler) Signup(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Signup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewISignupAuthHandler creates a new instance of ISignupAuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISignupAuthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISignupAuthHandler {
	mock := &ISignupAuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
