// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ISigninAuthHandler is an autogenerated mock type for the ISigninAuthHandler type
type ISigninAuthHandler struct {
	mock.Mock
}

// Signin provides a mock function with given fields: c
func (_m *ISigninAuthHandler) Signin(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Signin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewISigninAuthHandler creates a new instance of ISigninAuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISigninAuthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISigninAuthHandler {
	mock := &ISigninAuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
