// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"
	mysql "main/utils/db/mysql"

	mock "github.com/stretchr/testify/mock"

	request "main/features/room/model/request"
)

// IJoinRoomRepository is an autogenerated mock type for the IJoinRoomRepository type
type IJoinRoomRepository struct {
	mock.Mock
}

// FindOneAndUpdateRoom provides a mock function with given fields: ctx, roomID
func (_m *IJoinRoomRepository) FindOneAndUpdateRoom(ctx context.Context, roomID uint) error {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndUpdateRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, roomID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindOneAndUpdateUser provides a mock function with given fields: ctx, uID, roomID
func (_m *IJoinRoomRepository) FindOneAndUpdateUser(ctx context.Context, uID uint, roomID uint) error {
	ret := _m.Called(ctx, uID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndUpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, uID, roomID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindOneRoom provides a mock function with given fields: ctx, req
func (_m *IJoinRoomRepository) FindOneRoom(ctx context.Context, req *request.ReqJoin) (mysql.Rooms, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for FindOneRoom")
	}

	var r0 mysql.Rooms
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ReqJoin) (mysql.Rooms, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.ReqJoin) mysql.Rooms); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(mysql.Rooms)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.ReqJoin) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertOneRoomUser provides a mock function with given fields: ctx, roomUserDTO
func (_m *IJoinRoomRepository) InsertOneRoomUser(ctx context.Context, roomUserDTO mysql.RoomUsers) error {
	ret := _m.Called(ctx, roomUserDTO)

	if len(ret) == 0 {
		panic("no return value specified for InsertOneRoomUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, mysql.RoomUsers) error); ok {
		r0 = rf(ctx, roomUserDTO)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIJoinRoomRepository creates a new instance of IJoinRoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIJoinRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IJoinRoomRepository {
	mock := &IJoinRoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
