// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IOutRoomRepository is an autogenerated mock type for the IOutRoomRepository type
type IOutRoomRepository struct {
	mock.Mock
}

// FindOneAndDeleteRoomUser provides a mock function with given fields: ctx, uID, roomID
func (_m *IOutRoomRepository) FindOneAndDeleteRoomUser(ctx context.Context, uID uint, roomID uint) error {
	ret := _m.Called(ctx, uID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndDeleteRoomUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, uID, roomID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindOneAndUpdateRoom provides a mock function with given fields: ctx, roomID
func (_m *IOutRoomRepository) FindOneAndUpdateRoom(ctx context.Context, roomID uint) error {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndUpdateRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, roomID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindOneAndUpdateUser provides a mock function with given fields: ctx, uID
func (_m *IOutRoomRepository) FindOneAndUpdateUser(ctx context.Context, uID uint) error {
	ret := _m.Called(ctx, uID)

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndUpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, uID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIOutRoomRepository creates a new instance of IOutRoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOutRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOutRoomRepository {
	mock := &IOutRoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
