// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	request "main/features/room/model/request"

	mock "github.com/stretchr/testify/mock"
)

// IOutRoomUseCase is an autogenerated mock type for the IOutRoomUseCase type
type IOutRoomUseCase struct {
	mock.Mock
}

// Out provides a mock function with given fields: c, uID, req
func (_m *IOutRoomUseCase) Out(c context.Context, uID uint, req *request.ReqOut) error {
	ret := _m.Called(c, uID, req)

	if len(ret) == 0 {
		panic("no return value specified for Out")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *request.ReqOut) error); ok {
		r0 = rf(c, uID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIOutRoomUseCase creates a new instance of IOutRoomUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOutRoomUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOutRoomUseCase {
	mock := &IOutRoomUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
