// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	response "main/features/room/model/response"

	mock "github.com/stretchr/testify/mock"
)

// IUserListRoomRepository is an autogenerated mock type for the IUserListRoomRepository type
type IUserListRoomRepository struct {
	mock.Mock
}

// FindRoomUser provides a mock function with given fields: ctx, roomID
func (_m *IUserListRoomRepository) FindRoomUser(ctx context.Context, roomID uint) ([]response.User, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for FindRoomUser")
	}

	var r0 []response.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]response.User, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []response.User); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIUserListRoomRepository creates a new instance of IUserListRoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserListRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserListRoomRepository {
	mock := &IUserListRoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
