// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	response "main/features/users/model/response"

	mock "github.com/stretchr/testify/mock"
)

// IListUsersUseCase is an autogenerated mock type for the IListUsersUseCase type
type IListUsersUseCase struct {
	mock.Mock
}

// List provides a mock function with given fields: c
func (_m *IListUsersUseCase) List(c context.Context) (response.ResListUser, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 response.ResListUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (response.ResListUser, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) response.ResListUser); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(response.ResListUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIListUsersUseCase creates a new instance of IListUsersUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIListUsersUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IListUsersUseCase {
	mock := &IListUsersUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
