// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IAuthChatUseCase is an autogenerated mock type for the IAuthChatUseCase type
type IAuthChatUseCase struct {
	mock.Mock
}

// Auth provides a mock function with given fields: c, userID
func (_m *IAuthChatUseCase) Auth(c context.Context, userID uint) (string, error) {
	ret := _m.Called(c, userID)

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (string, error)); ok {
		return rf(c, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) string); ok {
		r0 = rf(c, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(c, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAuthChatUseCase creates a new instance of IAuthChatUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuthChatUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuthChatUseCase {
	mock := &IAuthChatUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
