// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// IMessageChatHandler is an autogenerated mock type for the IMessageChatHandler type
type IMessageChatHandler struct {
	mock.Mock
}

// Message provides a mock function with given fields: c
func (_m *IMessageChatHandler) Message(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIMessageChatHandler creates a new instance of IMessageChatHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMessageChatHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMessageChatHandler {
	mock := &IMessageChatHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
