// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	mysql "main/utils/db/mysql"

	mock "github.com/stretchr/testify/mock"
)

// IMessageChatUseCase is an autogenerated mock type for the IMessageChatUseCase type
type IMessageChatUseCase struct {
	mock.Mock
}

// Message provides a mock function with given fields: c, secret
func (_m *IMessageChatUseCase) Message(c context.Context, secret string) (*mysql.Chats, error) {
	ret := _m.Called(c, secret)

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 *mysql.Chats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*mysql.Chats, error)); ok {
		return rf(c, secret)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *mysql.Chats); ok {
		r0 = rf(c, secret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mysql.Chats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, secret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIMessageChatUseCase creates a new instance of IMessageChatUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMessageChatUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMessageChatUseCase {
	mock := &IMessageChatUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
