// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRoom = "rooms"

// Room mapped from table <rooms>
type Room struct {
	ID           int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CurrentCount int32          `gorm:"column:current_count" json:"current_count"`
	MaxCount     int32          `gorm:"column:max_count" json:"max_count"`
	MinCount     int32          `gorm:"column:min_count" json:"min_count"`
	Name         string         `gorm:"column:name" json:"name"`
	Password     string         `gorm:"column:password" json:"password"`
	State        string         `gorm:"column:state" json:"state"`
	Owner        string         `gorm:"column:owner" json:"owner"`
}

// TableName Room's table name
func (*Room) TableName() string {
	return TableNameRoom
}
