// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	mysql "main/utils/db/mysql"

	mock "github.com/stretchr/testify/mock"

	request "main/features/game/model/request"
)

// IDiscardGameRepository is an autogenerated mock type for the IDiscardGameRepository type
type IDiscardGameRepository struct {
	mock.Mock
}

// PlayerCheckTurn provides a mock function with given fields: c, req
func (_m *IDiscardGameRepository) PlayerCheckTurn(c context.Context, req *request.ReqDiscard) (mysql.RoomUsers, error) {
	ret := _m.Called(c, req)

	if len(ret) == 0 {
		panic("no return value specified for PlayerCheckTurn")
	}

	var r0 mysql.RoomUsers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ReqDiscard) (mysql.RoomUsers, error)); ok {
		return rf(c, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.ReqDiscard) mysql.RoomUsers); ok {
		r0 = rf(c, req)
	} else {
		r0 = ret.Get(0).(mysql.RoomUsers)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.ReqDiscard) error); ok {
		r1 = rf(c, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCardStateDiscard provides a mock function with given fields: c, req
func (_m *IDiscardGameRepository) UpdateCardStateDiscard(c context.Context, req *request.ReqDiscard) error {
	ret := _m.Called(c, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCardStateDiscard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ReqDiscard) error); ok {
		r0 = rf(c, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRoomUser provides a mock function with given fields: c, updateRoomUser
func (_m *IDiscardGameRepository) UpdateRoomUser(c context.Context, updateRoomUser mysql.RoomUsers) error {
	ret := _m.Called(c, updateRoomUser)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoomUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, mysql.RoomUsers) error); ok {
		r0 = rf(c, updateRoomUser)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIDiscardGameRepository creates a new instance of IDiscardGameRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDiscardGameRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDiscardGameRepository {
	mock := &IDiscardGameRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
