// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	request "main/features/game/model/request"

	mock "github.com/stretchr/testify/mock"
)

// IDiscardGameUseCase is an autogenerated mock type for the IDiscardGameUseCase type
type IDiscardGameUseCase struct {
	mock.Mock
}

// Discard provides a mock function with given fields: c, userID, req
func (_m *IDiscardGameUseCase) Discard(c context.Context, userID int, req *request.ReqDiscard) error {
	ret := _m.Called(c, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Discard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *request.ReqDiscard) error); ok {
		r0 = rf(c, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIDiscardGameUseCase creates a new instance of IDiscardGameUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDiscardGameUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDiscardGameUseCase {
	mock := &IDiscardGameUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
