// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	request "main/features/game/model/request"

	mock "github.com/stretchr/testify/mock"
)

// IDoraGameRepository is an autogenerated mock type for the IDoraGameRepository type
type IDoraGameRepository struct {
	mock.Mock
}

// CheckFirstPlayer provides a mock function with given fields: c, userID, roomID
func (_m *IDoraGameRepository) CheckFirstPlayer(c context.Context, userID int, roomID int) error {
	ret := _m.Called(c, userID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for CheckFirstPlayer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(c, userID, roomID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDoraCard provides a mock function with given fields: c, req
func (_m *IDoraGameRepository) UpdateDoraCard(c context.Context, req *request.ReqDora) error {
	ret := _m.Called(c, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDoraCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ReqDora) error); ok {
		r0 = rf(c, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIDoraGameRepository creates a new instance of IDoraGameRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDoraGameRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDoraGameRepository {
	mock := &IDoraGameRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
