// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	request "main/features/game/model/request"

	mock "github.com/stretchr/testify/mock"
)

// IDoraGameUseCase is an autogenerated mock type for the IDoraGameUseCase type
type IDoraGameUseCase struct {
	mock.Mock
}

// Dora provides a mock function with given fields: c, userID, req
func (_m *IDoraGameUseCase) Dora(c context.Context, userID int, req *request.ReqDora) error {
	ret := _m.Called(c, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Dora")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *request.ReqDora) error); ok {
		r0 = rf(c, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIDoraGameUseCase creates a new instance of IDoraGameUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDoraGameUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDoraGameUseCase {
	mock := &IDoraGameUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
