// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// IDoraGameHandler is an autogenerated mock type for the IDoraGameHandler type
type IDoraGameHandler struct {
	mock.Mock
}

// Dora provides a mock function with given fields: c
func (_m *IDoraGameHandler) Dora(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Dora")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIDoraGameHandler creates a new instance of IDoraGameHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDoraGameHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDoraGameHandler {
	mock := &IDoraGameHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
