// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	request "main/features/game/model/request"

	mock "github.com/stretchr/testify/mock"
)

// ILoanGameUseCase is an autogenerated mock type for the ILoanGameUseCase type
type ILoanGameUseCase struct {
	mock.Mock
}

// Loan provides a mock function with given fields: c, userID, req
func (_m *ILoanGameUseCase) Loan(c context.Context, userID uint, req *request.ReqLoan) error {
	ret := _m.Called(c, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Loan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *request.ReqLoan) error); ok {
		r0 = rf(c, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewILoanGameUseCase creates a new instance of ILoanGameUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewILoanGameUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ILoanGameUseCase {
	mock := &ILoanGameUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
