// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	request "main/features/game/model/request"

	mock "github.com/stretchr/testify/mock"
)

// INextTurnGameUseCase is an autogenerated mock type for the INextTurnGameUseCase type
type INextTurnGameUseCase struct {
	mock.Mock
}

// NextTurn provides a mock function with given fields: c, req
func (_m *INextTurnGameUseCase) NextTurn(c context.Context, req *request.ReqNextTurn) error {
	ret := _m.Called(c, req)

	if len(ret) == 0 {
		panic("no return value specified for NextTurn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ReqNextTurn) error); ok {
		r0 = rf(c, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewINextTurnGameUseCase creates a new instance of INextTurnGameUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewINextTurnGameUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *INextTurnGameUseCase {
	mock := &INextTurnGameUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
