// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	request "main/features/game/model/request"

	mock "github.com/stretchr/testify/mock"
)

// INextTurnGameRepository is an autogenerated mock type for the INextTurnGameRepository type
type INextTurnGameRepository struct {
	mock.Mock
}

// UpdatePlayerNextTurn provides a mock function with given fields: c, req
func (_m *INextTurnGameRepository) UpdatePlayerNextTurn(c context.Context, req *request.ReqNextTurn) error {
	ret := _m.Called(c, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePlayerNextTurn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ReqNextTurn) error); ok {
		r0 = rf(c, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewINextTurnGameRepository creates a new instance of INextTurnGameRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewINextTurnGameRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *INextTurnGameRepository {
	mock := &INextTurnGameRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
