// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	request "main/features/game/model/request"

	mock "github.com/stretchr/testify/mock"
)

// IOwnershipGameRepository is an autogenerated mock type for the IOwnershipGameRepository type
type IOwnershipGameRepository struct {
	mock.Mock
}

// UpdateCardState provides a mock function with given fields: c, req
func (_m *IOwnershipGameRepository) UpdateCardState(c context.Context, req *request.ReqOwnership) error {
	ret := _m.Called(c, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCardState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ReqOwnership) error); ok {
		r0 = rf(c, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRoomUserCardCount provides a mock function with given fields: c, req
func (_m *IOwnershipGameRepository) UpdateRoomUserCardCount(c context.Context, req *request.ReqOwnership) error {
	ret := _m.Called(c, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoomUserCardCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ReqOwnership) error); ok {
		r0 = rf(c, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIOwnershipGameRepository creates a new instance of IOwnershipGameRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOwnershipGameRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOwnershipGameRepository {
	mock := &IOwnershipGameRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
