// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	mysql "main/utils/db/mysql"

	mock "github.com/stretchr/testify/mock"

	request "main/features/game/model/request"
)

// IScoreCalculateGameRepository is an autogenerated mock type for the IScoreCalculateGameRepository type
type IScoreCalculateGameRepository struct {
	mock.Mock
}

// CheckCardCount provides a mock function with given fields: c, userID, req
func (_m *IScoreCalculateGameRepository) CheckCardCount(c context.Context, userID uint, req *request.ReqScoreCalculate) error {
	ret := _m.Called(c, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CheckCardCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *request.ReqScoreCalculate) error); ok {
		r0 = rf(c, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDoraCard provides a mock function with given fields: c, req
func (_m *IScoreCalculateGameRepository) GetDoraCard(c context.Context, req *request.ReqScoreCalculate) (mysql.Cards, error) {
	ret := _m.Called(c, req)

	if len(ret) == 0 {
		panic("no return value specified for GetDoraCard")
	}

	var r0 mysql.Cards
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ReqScoreCalculate) (mysql.Cards, error)); ok {
		return rf(c, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.ReqScoreCalculate) mysql.Cards); ok {
		r0 = rf(c, req)
	} else {
		r0 = ret.Get(0).(mysql.Cards)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.ReqScoreCalculate) error); ok {
		r1 = rf(c, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIScoreCalculateGameRepository creates a new instance of IScoreCalculateGameRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIScoreCalculateGameRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IScoreCalculateGameRepository {
	mock := &IScoreCalculateGameRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
