// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// IStartGameHandler is an autogenerated mock type for the IStartGameHandler type
type IStartGameHandler struct {
	mock.Mock
}

// Start provides a mock function with given fields: c
func (_m *IStartGameHandler) Start(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIStartGameHandler creates a new instance of IStartGameHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIStartGameHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *IStartGameHandler {
	mock := &IStartGameHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
