// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	request "main/features/game/model/request"

	mock "github.com/stretchr/testify/mock"
)

// IStartGameUseCase is an autogenerated mock type for the IStartGameUseCase type
type IStartGameUseCase struct {
	mock.Mock
}

// Start provides a mock function with given fields: c, uID, req
func (_m *IStartGameUseCase) Start(c context.Context, uID uint, req *request.ReqStart) error {
	ret := _m.Called(c, uID, req)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *request.ReqStart) error); ok {
		r0 = rf(c, uID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIStartGameUseCase creates a new instance of IStartGameUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIStartGameUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IStartGameUseCase {
	mock := &IStartGameUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
