// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	request "main/features/rooms/model/request"

	mock "github.com/stretchr/testify/mock"
)

// IReadyRoomsRepository is an autogenerated mock type for the IReadyRoomsRepository type
type IReadyRoomsRepository struct {
	mock.Mock
}

// FindOneAndUpdateRoomUser provides a mock function with given fields: ctx, uID, req
func (_m *IReadyRoomsRepository) FindOneAndUpdateRoomUser(ctx context.Context, uID uint, req *request.ReqReady) error {
	ret := _m.Called(ctx, uID, req)

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndUpdateRoomUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *request.ReqReady) error); ok {
		r0 = rf(ctx, uID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIReadyRoomsRepository creates a new instance of IReadyRoomsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIReadyRoomsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IReadyRoomsRepository {
	mock := &IReadyRoomsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
