// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	response "main/features/rooms/model/response"

	mock "github.com/stretchr/testify/mock"
)

// IUserListRoomsUseCase is an autogenerated mock type for the IUserListRoomsUseCase type
type IUserListRoomsUseCase struct {
	mock.Mock
}

// UserList provides a mock function with given fields: c, RoomID
func (_m *IUserListRoomsUseCase) UserList(c context.Context, RoomID uint) (response.ResUserListRoom, error) {
	ret := _m.Called(c, RoomID)

	if len(ret) == 0 {
		panic("no return value specified for UserList")
	}

	var r0 response.ResUserListRoom
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (response.ResUserListRoom, error)); ok {
		return rf(c, RoomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) response.ResUserListRoom); ok {
		r0 = rf(c, RoomID)
	} else {
		r0 = ret.Get(0).(response.ResUserListRoom)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(c, RoomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIUserListRoomsUseCase creates a new instance of IUserListRoomsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserListRoomsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserListRoomsUseCase {
	mock := &IUserListRoomsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
