name: deploy DEV

on:
  workflow_dispatch:
    branches:
      - dev

jobs:
  test:
    name: api server test
    runs-on: self-hosted
    steps:
      - name: check path
        run: pwd
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: prepare envs
        id: vars
        run: |
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      - name: go test
        run: |
          cd ./src
          go test -v ./...
  